### ISSUE TITLE
CheckableBootstrapTreeview.fill() needs to uncheck

### ISSUE THREAD

**Issue by mshriver** [RedHatQE/widgetastic.patternfly#42]
https://github.com/RedHatQE/widgetastic.patternfly/blob/master/src/widgetastic_patternfly/__init__.py#L1380

This fill method will only check nodes, and won't uncheck those that are filled.

I would like to enhance the fill by taking a more complex data structure with tuples of path and `check` boolean to check/uncheck within a fill context.

The current implementation is forcing callers to use check_node/uncheck_node in patterns that would be better served within a `fill()`

**Comment by mfalesni** [comment]
Makes sense :)
