### ISSUE TITLE
The usage example is incomplete

### ISSUE THREAD

**Issue by elyezer** [RedHatQE/widgetastic.patternfly#45]
The usage example on README file does not import everything needed

```
from widgetastic_patternfly import Button

class SomeView(View):
    add = Button('Add', classes=[Button.PRIMARY])
```

From where `View` comes from. It is probably from widgetastic.core but that is not clear for new comers. I think showing the import will clarify that and also make newcomers check core docs in order to know more about the View.

**Comment by psav** [comment]
Agree here, we should add this

**Comment by mfalesni** [comment]
cbe5161
